name: CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write # needed for creating releases
  packages: write # needed for creating releases

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [22]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: 'sbt'

    - name: Setup sbt
      uses: sbt/setup-sbt@v1
    
    - name: Run tests
      run: sbt test
    
    - name: Build package
      run: sbt Universal/packageBin
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: supercoder-package
        path: target/universal/supercoder-*.zip
        retention-days: 5

    - name: Create a Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: target/universal/supercoder-*.zip
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Cleanup before cache
      run: |
        rm -rf "$HOME/.ivy2/local" || true
        find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
        find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
        find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
        find $HOME/.sbt                              -name "*.lock"               -delete || true 